"""Add student learning activity

Revision ID: 5e6d36d577f2
Revises: f2d28f5f5a0f
Create Date: 2026-07-16 10:00:34.405867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e6d36d577f2'
down_revision = 'f2d28f5f5a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_learning_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_learning_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_learning_activities_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_learning_activities_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_learning_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_learning_activities_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_learning_activities_lesson_id'))

    op.drop_table('student_learning_activities')
    # ### end Alembic commands ###
