"""add recommendations table

Revision ID: 9cf21a5e5ca2
Revises: 7a5d9f3c2b10
Create Date: 2026-07-12 16:56:37.675083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf21a5e5ca2'
down_revision = '7a5d9f3c2b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('quizzes_lesson_id_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('quizzes_lesson_id_key'), ['lesson_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
