"""add file path to lesson resources

Revision ID: f2d28f5f5a0f
Revises: ffdfd75b20b5
Create Date: 2026-07-13 21:59:30.421890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d28f5f5a0f'
down_revision = 'ffdfd75b20b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_resources', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
