"""add current learning stage to progress

Revision ID: ffdfd75b20b5
Revises: 59cb16cd6d41
Create Date: 2026-07-13 00:20:22.801579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffdfd75b20b5'
down_revision = '59cb16cd6d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "current_learning_stage",
                sa.String(length=30),
                nullable=False,
                server_default="lesson"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_column('current_learning_stage')

    # ### end Alembic commands ###
